Numpy

In [1]:
import numpy as np #np is the alias name 

In [2]:
my_list=[2,3,4,5,6]

In [3]:
print(my_list)

[2, 3, 4, 5, 6]


In [4]:
type(my_list)

list

In [5]:
arr=np.array(my_list) #np.array() converts any list into an array

In [6]:
print(arr)

[2 3 4 5 6]


In [7]:
type(arr) #ndimentionalarray, n=1 i.e. 1D array

numpy.ndarray

In [12]:
#multinested array
my_list=[2,3,4,5,6]
my_list_2=[4,5,6,9,3]
my_list_3=[1,7,4,5,6]

In [13]:
arr_new=np.array([my_list,my_list_2,my_list_3])

In [14]:
print(arr_new)

[[2 3 4 5 6]
 [4 5 6 9 3]
 [1 7 4 5 6]]


In [23]:
print(arr_new.reshape(5,3))

[[2 3 4]
 [5 6 4]
 [5 6 9]
 [3 1 7]
 [4 5 6]]


In [24]:
print(arr_new.reshape(5,4))

ValueError: ignored

In [20]:
arr_new.shape #shows the number of rows and columns in the array

(3, 5)

In [15]:
type(arr_new) #n=2, 2D array

numpy.ndarray

In [18]:
my=[1,2,3,4]
my1=[6,7,8,9]
my2=[10,11,12,1]
my3=[15,26,27,2]

my_arr=np.array([my,my1,my2,my3])

In [19]:
print(my_arr)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12  1]
 [15 26 27  2]]


In [21]:
my_arr.shape

(4, 4)

In [25]:
#indexing and slicing 

In [26]:
print(arr)

[2 3 4 5 6]


In [27]:
arr[2]

4

In [28]:
arr[4]

6

In [29]:
arr[1:4]

array([3, 4, 5])

In [30]:
arr[2:]

array([4, 5, 6])

In [31]:
print(arr_new)

[[2 3 4 5 6]
 [4 5 6 9 3]
 [1 7 4 5 6]]


In [33]:
arr_new[0:2,1:4]

array([[3, 4, 5],
       [5, 6, 9]])

In [32]:
arr_new[1:,3:] #1: is applicable for rows and 3: is applicable for columns slicing

array([[9, 3],
       [5, 6]])